### ISSUE TITLE
Is "limit" the right name?

### ISSUE THREAD

**Issue by eyal-ka** [RamanujanMachine/ResearchTools#11] opened 2023-06-11 10:36 UTC
@RotemKalisch 

Are you sure this is called the limit? I feel like there should be a better name, maybe substitute? 

https://github.com/RamanujanMachine/ResearchTools/blob/0aa31e1247dc5500e235c0677f10729335030e23/ramanujan/matrix.py#LL48C11-L48C11

**Comment by RotemKalisch** [comment] 2023-06-15 11:45
> @RotemKalisch
> 
> Are you sure this is called the limit? I feel like there should be a better name, maybe substitute?
> 
> https://github.com/RamanujanMachine/ResearchTools/blob/0aa31e1247dc5500e235c0677f10729335030e23/ramanujan/matrix.py#LL48C11-L48C11

I'm open to suggestions (@rotelimelech @itaybthl)

**Comment by RotemKalisch** [comment] 2024-04-26 07:04
Closing this as this code has changed and the issue is irrelevant

**Closed by RotemKalisch** 2024-04-26 07:04 UTC
